# Generated by Django 5.0.6 on 2024-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанар')),
            ],
        ),
    ]
